[project]
name = "param-decomp-config"
version = "0.0.1"
description = "Torch-free pydantic config schema for Parameter Decomposition"
requires-python = "==3.13.*"
urls = { "Homepage" = "https://github.com/goodfire-ai/param-decomp" }
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "pydantic<2.12", # https://github.com/goodfire-ai/param-decomp/pull/232 , https://github.com/goodfire-ai/param-decomp/issues/221
    "numpy",
    "pyyaml",
    "annotated-types",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["param_decomp_config"]

[tool.setuptools.package-dir]
param_decomp_config = "."
