#!/usr/bin/env python
"""Generate one LR-sweep arm config from a profile's production config.

    python make_lr_arm.py <profile> <multiplier> <out.yaml>

An ARM is the production config with BOTH learning rates scaled by the same multiplier —
`pd.components_optimizer` and `pd.ci_fn_optimizer`, whose 3.2e-4 / 1.6e-4 the recipe couples
2:1 — and nothing else changed except the checkpoint cadence. In particular `pd.steps` stays
40000:

  * the cosine decay and every coefficient ramp are authored against `pd.steps`, so an arm
    authored with `steps: 2000` would compress the whole schedule into the probe and measure
    a different training run (measured: a 30-step trial already reads lr = 0.1 x max_val);
  * the winner is CONTINUED on its own run id, and resume byte-compares the pinned
    `launch_config.yaml` — an arm authored with `steps: 2000` could never become the real run.

So an arm runs to 40000 in principle and is INTERRUPTED after its step-2000 checkpoint. The
seed is NOT varied: with one seed the only difference between arms is the LR.

Run ids are hashed from `<profile>/lr<multiplier>` so arms can be added or dropped without
remapping ids onto existing run dirs (the same rule make_trials.py uses)."""

import hashlib
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from make_trials import PROFILES  # noqa: E402

PROBE_STEPS = 2000
"""Where an arm is interrupted and compared. Past the 500-step PPGD adversary ramp; the
imp-min/frequency ramps run to 10000, so every arm is equally mid-ramp here."""


def arm_run_id(profile: str, mult: float) -> str:
    digest = hashlib.blake2b(f"{profile}/lr{mult:g}".encode(), digest_size=4).hexdigest()
    return f"p-{digest}"


def build(profile: str, mult: float) -> dict:
    cfg = yaml.safe_load((HERE.parent / PROFILES[profile]["sota"]).read_text())
    for opt in ("components_optimizer", "ci_fn_optimizer"):
        lr = cfg["pd"][opt]["lr_schedule"]
        lr["max_val"] = float(f"{lr['max_val'] * mult:.6g}")
    cfg["run_name"] = f"{cfg['run_name']}-lr{mult:g}x"
    cfg["cadence"]["checkpointing"]["save_every"] = PROBE_STEPS
    cfg["cadence"]["checkpointing"]["retention"] = {"kind": "keep_last", "n": 1}
    return cfg


def main() -> None:
    profile, mult_s, out = sys.argv[1:4]
    mult = float(mult_s)
    cfg = build(profile, mult)
    lrs = tuple(
        cfg["pd"][o]["lr_schedule"]["max_val"] for o in ("components_optimizer", "ci_fn_optimizer")
    )
    Path(out).write_text(
        f"# GENERATED by make_lr_arm.py from ../{PROFILES[profile]['sota']} — LR sweep arm.\n"
        f"# LR x{mult:g}: components {lrs[0]:g}, ci_fn {lrs[1]:g}. steps stays 40000; the arm is\n"
        f"# INTERRUPTED after its step-{PROBE_STEPS} checkpoint and the winner is resumed to 40000.\n"
        f"# run id {arm_run_id(profile, mult)}\n" + yaml.safe_dump(cfg, sort_keys=False, width=100)
    )
    print(
        f"wrote {out}  (lr x{mult:g}: components {lrs[0]:g}, ci_fn {lrs[1]:g}, run id {arm_run_id(profile, mult)})"
    )


if __name__ == "__main__":
    main()
