#!/usr/bin/env python
"""Build the real run's config from the balanced recipe, folding in every measured result.

    python make_final_run.py --lr-mult 0.5 --c-mult 2 --rho <measured> -o <out.yaml>

Starts from `addsub-all-layers-4xh100-bal-perpos.yaml` (the balanced hidden recipe: per-point
weights restored to L18's by x32/14, and `per_position` normalization) and applies:

* `--lr-mult`  BOTH learning rates, which the recipe couples 2:1. The 2026-09-10 sweep
  measured 0.5x as the optimum at 32 blocks (score 2.953 against 4.864 at 0.125x and 43.5 at
  2x, mean of the last 5 `train/loss/total` at step 2000, seed 0 throughout). NOTE the sweep
  ran at C1x under BATCH normalization and the diluted hidden coefficients, so the optimum
  transfers only approximately to this objective.
* `--c-mult`   every entry of `sites.cs`. C is tiled across layers by schema — the chunkwise
  CI fn scans over chunks and asserts they are homogeneous in the per-slot C tuple — so C
  scales for all 32 blocks or none. Measured at C2x: 41.6 GB/rank of 80, 2.49 s/step.
* `--rho`      DIVIDES the three hidden recon coefficients. `per_position` restores the L18
  per-point WEIGHT but replaces the per-point QUANTITY with a different functional, whose
  value is larger wherever high-energy positions reconstruct well and low-energy ones badly.
  Dividing by the measured ratio keeps the L18 recon/sparsity exchange rate while still
  moving the pressure off the BOS position. `--rho 1` opts out and takes per_position's own
  scale. Measure it with `arms-4xh100/normcal.yaml` under `PD_LOG_ALT_HIDDEN_NORM=1`.
"""

import argparse
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "addsub-all-layers-4xh100-bal-perpos.yaml"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lr-mult", type=float, required=True)
    ap.add_argument("--c-mult", type=int, default=1)
    ap.add_argument("--rho", type=float, required=True)
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    cfg = yaml.safe_load(SOURCE.read_text())
    for opt in ("components_optimizer", "ci_fn_optimizer"):
        lr = cfg["pd"][opt]["lr_schedule"]
        lr["max_val"] = float(f"{lr['max_val'] * a.lr_mult:.6g}")
    if a.c_mult != 1:
        cs = cfg["decomposition"]["sites"]["cs"]
        cfg["decomposition"]["sites"]["cs"] = {k: v * a.c_mult for k, v in cs.items()}
    if a.rho != 1.0:
        for term in cfg["pd"]["hidden"]["recon"]:
            term["coeff"] = float(f"{term['coeff'] / a.rho:.6g}")
        for term in cfg["nontarget"]["hidden"]["recon"]:
            term["coeff"] = float(f"{term['coeff'] / a.rho:.6g}")
    cfg["run_name"] = "addsub-all-layers-4xh100-balanced-01"

    lrs = tuple(
        cfg["pd"][o]["lr_schedule"]["max_val"] for o in ("components_optimizer", "ci_fn_optimizer")
    )
    hid = [(t.get("name", t["type"]), t["coeff"]) for t in cfg["pd"]["hidden"]["recon"]]
    nth = [(t.get("name", t["type"]), t["coeff"]) for t in cfg["nontarget"]["hidden"]["recon"]]
    Path(a.out).write_text(
        f"# GENERATED by make_final_run.py from ../{SOURCE.name} — THE REAL RUN.\n"
        f"# LR x{a.lr_mult:g} (swept 2026-09-10): components {lrs[0]:g}, ci_fn {lrs[1]:g}.\n"
        f"# C x{a.c_mult:g}: {cfg['decomposition']['sites']['cs']}\n"
        f"# hidden coeffs / rho={a.rho:g} (per_position vs batch scale, measured): {hid} + {nth}\n"
        + yaml.safe_dump(cfg, sort_keys=False, width=100)
    )
    print(
        f"wrote {a.out}\n  LR {lrs}\n  cs {cfg['decomposition']['sites']['cs']}\n  hidden {hid}\n  nt-hidden {nth}"
    )


if __name__ == "__main__":
    main()
