#!/usr/bin/env python
"""Generate one reduced-block-count diagnostic config from a profile's production config.

    python scaletest_config.py <profile> <blocks> <start|''> <steps> <out.yaml> [K=V ...]

Trailing `K=V` pairs go into `runtime.launch_env.env`, which `as_env()` applies LAST and so
overrides every typed knob. That is the hook for NCCL diagnostics and workarounds
(`NCCL_DEBUG=INFO`, `NCCL_ALGO=Ring`, `NCCL_P2P_DISABLE=1`) without editing the production
config or needing a commit per experiment.

Called by scaletest.sh; a separate file rather than a heredoc so it can be tested, and so
`__file__` is real (a stdin script has no reliable one)."""

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from make_trials import PROFILES  # noqa: E402

N_LAYER = 32


def build(
    profile: str, blocks: int, start: str, steps: int, env: dict[str, str] | None = None
) -> tuple[dict, int]:
    cfg = yaml.safe_load((HERE.parent / PROFILES[profile]["sota"]).read_text())
    s = int(start) if start else N_LAYER - blocks
    assert s >= 0 and s + blocks <= N_LAYER, (s, blocks, N_LAYER)
    cfg["decomposition"]["sites"]["layers"] = {"kind": "range", "start": s, "end": s + blocks}
    # The hidden points MUST start at the first decomposed block. A point upstream of every
    # decomposed site cannot change under masking, so it contributes guaranteed zeros to the
    # point mean and `assert_hidden_acts_reconstruction_points` refuses the run — which is
    # exactly what a naive block-count change hit on 2026-09-10. The production config lists
    # all 32 only because it decomposes all 32; the 1- and 4-block reference recipes list
    # `first_decomposed..31` for this reason.
    cfg["pd"]["hidden"]["points"] = [f"layers.{i}.mlp.down_proj.out" for i in range(s, N_LAYER)]
    cfg["run_name"] = f"scaletest-{blocks}L"
    cfg["pd"]["steps"] = steps
    cfg["cadence"]["train_log_every"] = 10
    cfg["cadence"]["checkpointing"] = {"kind": "none"}
    cfg.pop("wandb", None)
    if env:
        cfg["runtime"].setdefault("launch_env", {}).setdefault("env", {}).update(env)
    return cfg, s


def main() -> None:
    profile, blocks, start, steps, out = sys.argv[1:6]
    env = dict(pair.split("=", 1) for pair in sys.argv[6:])
    cfg, s = build(profile, int(blocks), start, int(steps), env)
    Path(out).write_text(
        f"# GENERATED by scaletest.sh from ../{PROFILES[profile]['sota']} — diagnostic.\n"
        f"# {blocks} decomposed blocks (layers {s}..{s + int(blocks) - 1}), "
        f"{int(blocks) * 7} sites, {steps} steps, {len(cfg['pd']['hidden']['points'])} hidden points.\n"
        + (f"# extra env: {env}\n" if env else "")
        + yaml.safe_dump(cfg, sort_keys=False, width=100)
    )
    print(
        f"layers {s}..{s + int(blocks) - 1}  sites {int(blocks) * 7}  "
        f"hidden points {len(cfg['pd']['hidden']['points'])}"
    )


if __name__ == "__main__":
    main()
