"""The trainer's internal `ExperimentConfig` runtime dataclasses — the typed config the
generic engine (`run.py::run_decomposition_training`) and `run_state.init_train_state`
consume.

These are pure runtime structures: optimizer LRs, cadence, the resolved eval knobs, the
CI-fn architecture. They are domain-agnostic — `target` is typed by the `TargetSites`
protocol (just `.sites`), `data` is `DataConfig | None` (None for a positionless toy).
The YAML→dataclass CONVERSION (reading the canonical `ExperimentConfig[T, D]` pydantic
schema and asserting the implemented subspace) is COMPOSITION and lives lab-side:
`param_decomp_lab/experiments/config.py` carries the shared-algorithm conversion
(`convert_shared_algorithm_config` / `run_instance` / `layerwise_mlp_ci_arch` /
`toy_ci_arch`), and each experiment's `run.py` builds the rest of its `ExperimentConfig`.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol

from param_decomp.ci_fn import CIArch
from param_decomp.ci_fn_mlp import GlobalMLPCIArch, MLPCIArch
from param_decomp.configs import AnyLossMetricConfig, ResumeProvenance, WandbConfig
from param_decomp.lm import SiteC

CIFnArch = CIArch | MLPCIArch | GlobalMLPCIArch


class TargetSites(Protocol):
    """The only thing the generic engine needs from a target config: its decomposed
    sites. LM target configs live lab-side; non-LM targets (the toys) live in the lab
    and supply their own config dataclass — the core never names them."""

    @property
    def sites(self) -> tuple[SiteC, ...]: ...


WeightsDtype = Literal["float32", "bfloat16"]


@dataclass(frozen=True)
class DataConfig:
    """The LM pre-tokenized parquet data source. `None` on `ExperimentConfig` for a
    non-LM (toy) run, whose synthetic data is generated by its lab `sample_batch`."""

    dir: Path
    seq_len: int
    global_batch: int


@dataclass(frozen=True)
class VUOptimizerConfig:
    lr: float
    grad_clip_norm: float


@dataclass(frozen=True)
class CIOptimizerConfig:
    lr: float


@dataclass(frozen=True)
class FaithWarmupConfig:
    steps: int
    lr: float


@dataclass(frozen=True)
class DenseLogPhase:
    every: int
    until_step: int


@dataclass(frozen=True)
class CadenceConfig:
    log_every: int
    save_every: int
    keep_last: int
    dense_log_phase: DenseLogPhase | None


@dataclass(frozen=True)
class EvalPGDConfig:
    """Fresh sign-PGD recon probe (torch eval `PGDReconLoss`: init random, source
    shared across batch and positions)."""

    n_steps: int
    step_size: float


@dataclass(frozen=True)
class AttnPatternsEvalConfig:
    """In-loop attention-pattern recon metrics (torch `CIMaskedAttnPatternsReconLoss` /
    `StochasticAttnPatternsReconLoss`). Q/K are read from the decomposed `*q_proj`/`*k_proj`
    sites; the attention recipe (RoPE/GQA/head-dim) is read from the target — so no
    config-side n_heads/paths are threaded here. The flags select which variants run."""

    ci_masked: bool
    stochastic: bool


@dataclass(frozen=True)
class EvalConfig:
    """In-loop eval pass (torch `EvalLoop` analog). The FAST scalar tier runs every
    `every` steps; the SLOW/plot tier (CI histograms, activation density, mean-CI,
    hidden-acts recon) runs every `slow_every` steps, reusing the same eval batches
    (SPEC S28/S29). `rounding_threshold` binarises CI for the CE/KL `rounded_masked`
    variant; `ci_alive_threshold` is the CI-L0 aliveness cutoff."""

    batch_size: int
    every: int
    n_steps: int
    slow_every: int
    """The slow/plot tier cadence — a multiple of `every` (torch `EvalLoop.slow_every`),
    so the slow tier lands on a fast-eval step and reuses its eval batches."""
    slow_on_first_step: bool
    """Render the slow tier at the FIRST eval step too (torch parity), not only at
    `slow_every` multiples."""
    slow_n_batches_accum: int | None
    """The torch `CIHistograms.n_batches_accum` cap on the histogram raw-value sample
    (None caps nothing). Read from the `CIHistograms` eval metric when present."""
    rounding_threshold: float
    ci_alive_threshold: float
    l0_groups: dict[str, tuple[str, ...]] | None
    """torch CI_L0 `groups`: fnmatch site patterns whose member L0s sum into a
    group-named key. None = per-site keys only."""
    pgd: EvalPGDConfig | None
    attn_patterns: AttnPatternsEvalConfig | None


@dataclass(frozen=True)
class ExperimentConfig:
    run_name: str
    """Human-readable display name (the wandb run NAME)."""
    run_id: str
    """Canonical `p-<8hex>` id (wandb run ID + run-dir name) — the torch
    `generate_run_id` convention, making the run a first-class citizen of the
    `runs/<id>/` postprocess world. Minted at submit time by `pd-lm`."""
    out_dir: Path
    seed: int
    steps: int
    target: TargetSites
    """The decomposed target config — only its `sites` are read by the generic engine. An
    LM target config (lab-side) or a lab toy target config (satisfying `TargetSites`)."""
    data: DataConfig | None
    """The LM parquet data source; `None` for a toy run (its synthetic data lives in the
    lab provider's `sample_batch`)."""
    loss_metrics: tuple[AnyLossMetricConfig, ...]
    """The shared `pd.loss_metrics` configs, verbatim and in yaml order (order is
    RNG-load-bearing — see `build_recon_terms`)."""
    n_mask_samples: int
    sampling: Literal["continuous", "binomial"]
    remat_recon_forwards: bool
    vu_optimizer: VUOptimizerConfig
    ci_optimizer: CIOptimizerConfig
    ci_fn: CIFnArch
    faith_warmup: FaithWarmupConfig
    cadence: CadenceConfig
    eval: EvalConfig | None
    wandb: WandbConfig | None
    resume_provenance: ResumeProvenance | None
    """Set on a fine-tune run: the parent run dir + step to initialize V/U + ci_fn from
    (SPEC S33). `None` for a fresh-from-init run. Records lineage in wandb.config."""

    @property
    def run_dir(self) -> Path:
        return self.out_dir / self.run_id
